//
//  AffirmationDatabase.swift
//  DailyGlow
//
//  1000+ curated affirmations organized by category
//  This is the content that keeps users coming back! 💰
//

import Foundation

// MARK: - Affirmation Database
struct AffirmationDatabase {
    
    // MARK: - Motivation (99 affirmations)
    static let motivation: [String] = [
        "I am unstoppable in pursuing my dreams",
        "Every day I grow stronger and more capable",
        "I have the power to create positive change",
        "My potential is limitless and expanding",
        "I am becoming the best version of myself",
        "Challenges only make me stronger",
        "I am driven by passion and purpose",
        "Success flows naturally to me",
        "I take bold action toward my goals",
        "My determination knows no bounds",
        "I am capable of achieving greatness",
        "Every obstacle is an opportunity in disguise",
        "I am fueled by ambition and focus",
        "My willpower is unshakeable",
        "I embrace challenges with enthusiasm",
        "I am committed to my personal growth",
        "My motivation comes from within",
        "I persist until I succeed",
        "I am a powerful creator of my reality",
        "Every step forward is progress",
        "I choose to rise above limitations",
        "My energy and drive inspire others",
        "I am relentless in pursuit of excellence",
        "I transform obstacles into stepping stones",
        "My dedication leads to remarkable results",
        "I am worthy of success and achievement",
        "I wake up motivated and ready to conquer",
        "My actions align with my highest goals",
        "I am disciplined and focused",
        "Every day brings new opportunities",
        "I am the architect of my destiny",
        "My hard work always pays off",
        "I embrace the journey of self-improvement",
        "I am stronger than my excuses",
        "My passion fuels my perseverance",
        "I attract success through positive action",
        "I am committed to excellence in all I do",
        "My mindset creates my reality",
        "I push through barriers with ease",
        "I am designed for greatness",
        "Every challenge builds my character",
        "I am fearless in pursuing what I want",
        "My goals are within reach",
        "I take consistent action daily",
        "I am powered by purpose",
        "My resilience is my superpower",
        "I turn setbacks into comebacks",
        "I am unstoppable when I believe",
        "My potential grows every single day",
        "I am worthy of my biggest dreams",
        "I choose progress over perfection",
        "My determination defines my success",
        "I am building an extraordinary life",
        "Every effort I make matters",
        "I am capable of incredible things",
        "My drive pushes me forward",
        "I embrace growth and change",
        "I am motivated by my vision",
        "My success is inevitable",
        "I am stronger than yesterday",
        "I take ownership of my life",
        "My ambitions are valid and achievable",
        "I am creating momentum daily",
        "Every day I level up",
        "I am focused on what matters most",
        "My persistence will be rewarded",
        "I am hungry for success",
        "My energy attracts opportunities",
        "I am in control of my destiny",
        "Every action brings me closer to my goals",
        "I am worthy of an amazing life",
        "My dedication is unmatched",
        "I rise to every challenge",
        "I am empowered to achieve anything",
        "My motivation is constant and strong",
        "I believe in my ability to succeed",
        "Every moment is a chance to improve",
        "I am committed to my dreams",
        "My success story is being written now",
        "I am bold and courageous",
        "My efforts compound over time",
        "I am destined for remarkable things",
        "Every day I move closer to my vision",
        "I am a force of positive change",
        "My potential is being unlocked",
        "I am ready for the next level",
        "My passion keeps me going",
        "I am building something incredible",
        "Every setback is a setup for comeback",
        "I am worthy of celebration",
        "My journey is uniquely mine",
        "I am exactly where I need to be",
        "My future is bright and promising",
        "I am making progress every moment",
        "My dreams are becoming reality",
        "I am grateful for my ambition",
        "Every day I choose to show up",
        "I am living my purpose",
        "My success inspires others"
    ]
    
    // MARK: - Self Love (99 affirmations)
    static let selfLove: [String] = [
        "I am worthy of love exactly as I am",
        "I accept myself completely and unconditionally",
        "I am enough, just as I am",
        "I deserve all the good things life offers",
        "I love and approve of myself",
        "I am beautiful inside and out",
        "My imperfections make me unique",
        "I treat myself with kindness and respect",
        "I am deserving of happiness",
        "I celebrate who I am becoming",
        "I am proud of myself",
        "My self-worth is not up for debate",
        "I honor my needs and feelings",
        "I am gentle with myself",
        "I embrace all parts of who I am",
        "I am my own best friend",
        "My value is inherent and constant",
        "I forgive myself for past mistakes",
        "I am worthy of self-care",
        "I speak kindly to myself",
        "I am deserving of my own love",
        "My happiness matters",
        "I choose myself every day",
        "I am comfortable in my own skin",
        "I radiate self-confidence",
        "I am at peace with who I am",
        "My self-love grows stronger daily",
        "I deserve to take up space",
        "I am learning to love myself more",
        "I am worthy of respect",
        "My feelings are valid",
        "I trust myself completely",
        "I am allowed to prioritize myself",
        "I embrace my authentic self",
        "I am whole and complete",
        "My journey is worthy of love",
        "I release self-judgment",
        "I am kind to my body",
        "I celebrate my progress",
        "I deserve peace and joy",
        "I am lovable as I am",
        "My heart is full of self-compassion",
        "I accept compliments gracefully",
        "I am worthy of good things",
        "I honor my boundaries",
        "I am proud of my growth",
        "My self-love is unconditional",
        "I embrace my journey",
        "I am deserving of rest",
        "I appreciate my unique qualities",
        "I am allowed to say no",
        "My needs are important",
        "I love the person I am becoming",
        "I am gentle with my heart",
        "I deserve to be happy",
        "I accept my emotions",
        "I am worthy of care",
        "My soul is beautiful",
        "I choose self-love daily",
        "I am at home in my body",
        "I celebrate my individuality",
        "I am deserving of kindness",
        "My spirit is radiant",
        "I trust my inner wisdom",
        "I am complete within myself",
        "I embrace self-acceptance",
        "I am worthy of abundance",
        "My self-worth is unshakeable",
        "I love myself unconditionally",
        "I am allowed to shine",
        "I appreciate who I am",
        "I am deserving of love",
        "My heart knows my worth",
        "I release the need for approval",
        "I am proud of my heart",
        "I deserve my own compassion",
        "I am worthy of my dreams",
        "My authentic self is beautiful",
        "I honor my truth",
        "I am enough today",
        "I embrace my whole self",
        "I am deserving of grace",
        "My spirit is worthy",
        "I choose to love myself",
        "I am valuable beyond measure",
        "I treat myself with love",
        "I am worthy of peace",
        "My self-love is powerful",
        "I accept myself fully",
        "I am deserving of joy",
        "I embrace my worthiness",
        "I am kind to myself always",
        "My heart is worthy of love",
        "I celebrate being me",
        "I am proud of who I am",
        "I deserve unconditional love",
        "I am beautiful as I am",
        "My worth is infinite",
        "I love every part of me"
    ]
    
    // MARK: - Confidence (99 affirmations)
    static let confidence: [String] = [
        "I radiate confidence and self-assurance",
        "I trust my intuition completely",
        "I am comfortable being my authentic self",
        "My confidence grows stronger every day",
        "I believe in my abilities",
        "I express my true self freely",
        "I am secure in who I am",
        "I walk with purpose and power",
        "I am bold and fearless",
        "My presence commands respect",
        "I trust my decisions",
        "I am confident in my skin",
        "I speak my truth with ease",
        "I am worthy of being heard",
        "My voice matters",
        "I embrace new challenges confidently",
        "I am poised and self-assured",
        "I believe in my unique gifts",
        "I stand tall in my power",
        "I am confident in my worth",
        "I face fears with courage",
        "I am proud to be me",
        "My opinions are valuable",
        "I trust my path",
        "I am unafraid to be myself",
        "I radiate strength and grace",
        "I am confident in my journey",
        "I believe in my potential",
        "I am secure and grounded",
        "My self-belief is unshakeable",
        "I own my power",
        "I am confident in my choices",
        "I trust my inner strength",
        "I am worthy of success",
        "I carry myself with dignity",
        "I am fearless and bold",
        "My confidence is magnetic",
        "I believe in myself deeply",
        "I am comfortable taking risks",
        "I trust my capabilities",
        "I am confident in my vision",
        "I embrace my personal power",
        "I am self-assured and calm",
        "I believe in my dreams",
        "I am confident in my value",
        "I trust my unique journey",
        "I am bold in my actions",
        "My confidence inspires others",
        "I am secure in my identity",
        "I believe in my strength",
        "I am confident in my purpose",
        "I trust myself completely",
        "I am proud of my confidence",
        "I embrace my authentic power",
        "I am fearless in pursuit of growth",
        "My self-trust is absolute",
        "I am confident and capable",
        "I believe in my wisdom",
        "I am secure in my decisions",
        "I trust my heart",
        "I am bold and brave",
        "My confidence comes from within",
        "I am worthy of confidence",
        "I believe in my path",
        "I am self-assured daily",
        "I trust my instincts",
        "I am confident in my abilities",
        "I embrace my inner warrior",
        "I am secure in my worth",
        "I believe in myself always",
        "I am bold in my authenticity",
        "My confidence is growing",
        "I am fearless and free",
        "I trust my life journey",
        "I am confident in my growth",
        "I believe in my future",
        "I am secure and strong",
        "I trust my personal power",
        "I am confident in my essence",
        "I embrace my boldness",
        "I am self-assured and peaceful",
        "I believe in my resilience",
        "I am confident in my spirit",
        "I trust my authentic self",
        "I am bold and brilliant",
        "My confidence shines bright",
        "I am worthy of self-trust",
        "I believe in my courage",
        "I am secure in my being",
        "I trust my inner light",
        "I am confident and free",
        "I embrace my natural confidence",
        "I am fearless in being me",
        "My self-belief empowers me",
        "I am confident in my soul",
        "I believe in my magic",
        "I am secure and confident",
        "I trust myself fully",
        "I am boldly myself"
    ]
    
    // MARK: - Success (99 affirmations)
    static let success: [String] = [
        "Success flows to me easily and effortlessly",
        "I attract abundance in all areas of life",
        "Every day I move closer to my goals",
        "I am a magnet for success and prosperity",
        "My success inspires others to achieve",
        "I am destined for greatness",
        "Opportunities come to me naturally",
        "I create my own success story",
        "I am worthy of massive success",
        "My work creates lasting impact",
        "I attract wealth and opportunity",
        "I am successful in all I pursue",
        "My ideas lead to great success",
        "I am building lasting prosperity",
        "Success is my natural state",
        "I achieve my goals with ease",
        "I am surrounded by abundance",
        "My talents lead to success",
        "I am open to receiving success",
        "I create value everywhere I go",
        "My success benefits everyone",
        "I am prosperous and thriving",
        "Wealth flows to me freely",
        "I am deserving of success",
        "My career is flourishing",
        "I attract successful people",
        "I am living my successful life",
        "My efforts create abundance",
        "I am financially prosperous",
        "Success comes naturally to me",
        "I am achieving great things",
        "My life is filled with success",
        "I create opportunities daily",
        "I am worthy of wealth",
        "My success is multiplying",
        "I attract positive outcomes",
        "I am a successful person",
        "Prosperity is my birthright",
        "I achieve everything I desire",
        "My success is guaranteed",
        "I am living abundantly",
        "Wealth and success find me",
        "I am destined to prosper",
        "My goals manifest perfectly",
        "I am a success magnet",
        "Abundance surrounds me always",
        "I create my wealthy reality",
        "My success story continues",
        "I am thriving in all ways",
        "Prosperity flows through me",
        "I achieve with excellence",
        "My life reflects success",
        "I am blessed with abundance",
        "Success is inevitable for me",
        "I attract amazing opportunities",
        "My wealth is growing daily",
        "I am living my best life",
        "Success supports my dreams",
        "I am prospering now",
        "My future is prosperous",
        "I create abundant success",
        "Wealth comes easily to me",
        "I am achieving mastery",
        "My success elevates others",
        "I attract endless prosperity",
        "I am worthy of riches",
        "Success loves me",
        "My life is a success",
        "I prosper in all I do",
        "Abundance is my reality",
        "I am succeeding daily",
        "My goals are achieved",
        "I live in prosperity",
        "Success is mine now",
        "I attract wealth easily",
        "My prosperity expands",
        "I am achieving greatness",
        "Success flows freely to me",
        "I am abundantly blessed",
        "My success is permanent",
        "I create prosperous outcomes",
        "Wealth embraces me",
        "I am living successfully",
        "My abundance overflows",
        "I succeed effortlessly",
        "Prosperity loves me",
        "I am wealthy and successful",
        "Success fills my life",
        "I attract only the best",
        "My prosperity is endless",
        "I achieve all my dreams",
        "Success is my companion",
        "I am thriving financially",
        "My wealth is infinite",
        "I succeed in everything",
        "Abundance is everywhere",
        "I am prosperous always",
        "Success defines my life",
        "I am forever successful"
    ]
    
    // MARK: - Gratitude (99 affirmations)
    static let gratitude: [String] = [
        "I am grateful for all blessings in my life",
        "Gratitude fills my heart and guides my actions",
        "I appreciate the abundance surrounding me",
        "Every day I find new reasons to be thankful",
        "My life is full of things to be grateful for",
        "I am thankful for this present moment",
        "Gratitude transforms my perspective",
        "I appreciate the gift of today",
        "I am grateful for my journey",
        "Thankfulness opens doors for me",
        "I appreciate every experience",
        "Gratitude is my daily practice",
        "I am thankful for my growth",
        "I appreciate the love in my life",
        "Gratitude brings me peace",
        "I am grateful for my health",
        "I appreciate my unique path",
        "Thankfulness fills my soul",
        "I am grateful for new beginnings",
        "I appreciate every lesson learned",
        "Gratitude elevates my spirit",
        "I am thankful for my strength",
        "I appreciate life's simple joys",
        "Gratitude heals my heart",
        "I am grateful for abundance",
        "I appreciate my blessings daily",
        "Thankfulness is my superpower",
        "I am grateful for love",
        "I appreciate this beautiful life",
        "Gratitude multiplies my blessings",
        "I am thankful for today",
        "I appreciate my resilience",
        "Gratitude changes everything",
        "I am grateful for opportunities",
        "I appreciate my support system",
        "Thankfulness guides my day",
        "I am grateful for peace",
        "I appreciate my progress",
        "Gratitude expands my joy",
        "I am thankful for growth",
        "I appreciate every sunrise",
        "Gratitude is my foundation",
        "I am grateful for my life",
        "I appreciate my journey fully",
        "Thankfulness brings abundance",
        "I am grateful for this breath",
        "I appreciate my experiences",
        "Gratitude lifts my spirit",
        "I am thankful for blessings",
        "I appreciate my strength",
        "Gratitude fills my days",
        "I am grateful for love received",
        "I appreciate every moment",
        "Thankfulness is my choice",
        "I am grateful for my path",
        "I appreciate life deeply",
        "Gratitude opens my heart",
        "I am thankful for peace",
        "I appreciate my courage",
        "Gratitude transforms me",
        "I am grateful for joy",
        "I appreciate my wisdom",
        "Thankfulness empowers me",
        "I am grateful for hope",
        "I appreciate my heart",
        "Gratitude is my practice",
        "I am thankful for light",
        "I appreciate my soul",
        "Gratitude grounds me",
        "I am grateful for faith",
        "I appreciate my gifts",
        "Thankfulness inspires me",
        "I am grateful for grace",
        "I appreciate my truth",
        "Gratitude connects me",
        "I am thankful for purpose",
        "I appreciate my presence",
        "Gratitude flows through me",
        "I am grateful for calm",
        "I appreciate my spirit",
        "Thankfulness heals me",
        "I am grateful for wonder",
        "I appreciate my awareness",
        "Gratitude blesses me",
        "I am thankful for serenity",
        "I appreciate my being",
        "Gratitude enriches me",
        "I am grateful for miracles",
        "I appreciate my consciousness",
        "Thankfulness sustains me",
        "I am grateful for harmony",
        "I appreciate my existence",
        "Gratitude defines me",
        "I am thankful for beauty",
        "I appreciate my wholeness",
        "Gratitude completes me",
        "I am grateful for everything",
        "I appreciate life itself",
        "Thankfulness is my essence"
    ]
    
    // MARK: - Peace (81 affirmations)
    static let peace: [String] = [
        "Peace flows through me like a gentle river",
        "I am centered, calm, and at peace",
        "I release all worries and embrace tranquility",
        "My mind is clear and my heart is peaceful",
        "I choose peace over perfection",
        "Serenity fills every cell of my body",
        "I am at peace with myself and the world",
        "Calmness is my natural state",
        "I breathe in peace and exhale tension",
        "My soul is tranquil and still",
        "I find peace in every moment",
        "Stillness resides within me",
        "I am surrounded by peaceful energy",
        "My thoughts are calm and clear",
        "Peace guides my actions",
        "I release stress with ease",
        "Tranquility is my companion",
        "I am grounded and serene",
        "Peace lives in my heart",
        "I embrace inner stillness",
        "My spirit is at rest",
        "I choose calm over chaos",
        "Peace radiates from within",
        "I am free from anxiety",
        "Serenity is my gift",
        "I rest in peaceful awareness",
        "My being is tranquil",
        "I attract peaceful experiences",
        "Calm energy surrounds me",
        "I am at ease always",
        "Peace is my foundation",
        "I release all tension now",
        "My life flows peacefully",
        "I embrace gentle calm",
        "Stillness comforts me",
        "I am peacefully present",
        "Tranquility heals me",
        "My mind rests easy",
        "I choose inner peace",
        "Serenity guides me",
        "I am calm and collected",
        "Peace fills my days",
        "I breathe peaceful energy",
        "My heart knows peace",
        "I rest in calmness",
        "Tranquility is mine",
        "I am serenely happy",
        "Peace embraces me",
        "My soul finds rest",
        "I live peacefully",
        "Calm is my nature",
        "I attract serenity",
        "Peace flows freely",
        "My spirit is calm",
        "I embrace quiet peace",
        "Stillness surrounds me",
        "I am deeply peaceful",
        "Tranquility fills me",
        "My being is serene",
        "I choose calmness daily",
        "Peace is my choice",
        "I rest in stillness",
        "Serenity is natural",
        "My life is peaceful",
        "I breathe in calm",
        "Peace defines me",
        "I am tranquil now",
        "Calm energy fills me",
        "My heart is at peace",
        "I embrace serenity",
        "Stillness heals me",
        "I am peacefully aligned",
        "Tranquility is home",
        "My mind is peaceful",
        "I live in calm",
        "Peace surrounds me",
        "I am gently at ease",
        "Serenity flows within",
        "My soul is peaceful",
        "I rest in peace",
        "Calm is my essence"
    ]
    
    // MARK: - Health (81 affirmations)
    static let health: [String] = [
        "My body is healthy, strong, and full of energy",
        "I make choices that nourish my mind, body, and soul",
        "Every cell in my body radiates health and vitality",
        "I am grateful for my body and treat it with respect",
        "I am becoming healthier and stronger every day",
        "My immune system is powerful and protective",
        "I listen to my body's wisdom",
        "Health flows through me naturally",
        "I am vibrant and full of life",
        "My body heals itself perfectly",
        "I choose foods that fuel my wellness",
        "Energy and vitality are my natural state",
        "I am in tune with my body's needs",
        "My health improves every single day",
        "I breathe deeply and feel alive",
        "My body is a temple of wellness",
        "I am strong and capable",
        "Health is my birthright",
        "I honor my body's signals",
        "Vitality runs through my veins",
        "I am committed to my wellbeing",
        "My body supports my dreams",
        "I radiate healthy energy",
        "Wellness is my priority",
        "I am balanced and healthy",
        "My health is my wealth",
        "I nourish myself with love",
        "Energy flows freely through me",
        "I am grateful for my vitality",
        "My body is resilient",
        "I choose wellness daily",
        "Health empowers me",
        "I am full of life force",
        "My body is healing",
        "I embrace healthy habits",
        "Vitality is my nature",
        "I am thriving physically",
        "My health supports my life",
        "I honor my wellness journey",
        "Energy is abundant in me",
        "I am healthy and whole",
        "My body loves me back",
        "I radiate wellness",
        "Health is natural to me",
        "I am vitally alive",
        "My systems function perfectly",
        "I embrace my body",
        "Wellness fills my being",
        "I am healthier than ever",
        "My vitality increases daily",
        "I celebrate my health",
        "Energy is my companion",
        "I am fully nourished",
        "Health flows to me",
        "My body is powerful",
        "I thrive with vitality",
        "Wellness is my reality",
        "I am energetically strong",
        "My health is vibrant",
        "I embrace vitality",
        "Energy supports me",
        "I am glowing with health",
        "My body is balanced",
        "I radiate life force",
        "Wellness embraces me",
        "I am physically powerful",
        "Health is mine now",
        "My vitality shines",
        "I celebrate wellness",
        "Energy is unlimited",
        "I am optimally healthy",
        "My body thrives",
        "I embrace health fully",
        "Vitality defines me",
        "I am wellness embodied",
        "Health surrounds me",
        "My energy is limitless",
        "I am vibrantly healthy",
        "Wellness is my gift",
        "I thrive in health",
        "My body is grateful"
    ]
    
    // MARK: - Love (81 affirmations)
    static let love: [String] = [
        "I am surrounded by love every day",
        "Love flows to me and through me",
        "I am worthy of deep, meaningful love",
        "My heart is open to giving and receiving love",
        "Love is my natural state of being",
        "I attract loving relationships",
        "My life is filled with love",
        "I radiate love wherever I go",
        "Love finds me easily",
        "I am loved beyond measure",
        "My relationships are loving and supportive",
        "Love guides all my interactions",
        "I give love freely and openly",
        "I am a magnet for love",
        "Love heals all wounds",
        "I deserve unconditional love",
        "My heart overflows with love",
        "Love is always present in my life",
        "I attract my soulmate",
        "Love enriches my existence",
        "I am loving and lovable",
        "My capacity for love is infinite",
        "Love multiplies in my life",
        "I embrace love fully",
        "My relationships bring me joy",
        "Love is my superpower",
        "I am open to love",
        "Love surrounds me always",
        "My heart knows love",
        "I attract healthy love",
        "Love fills my days",
        "I am worthy of romance",
        "My love life flourishes",
        "Love comes naturally to me",
        "I embrace loving connections",
        "My heart is full",
        "Love blesses my life",
        "I radiate loving energy",
        "Love supports my growth",
        "I am deeply loved",
        "My relationships thrive",
        "Love is my foundation",
        "I give love generously",
        "Love returns to me multiplied",
        "My heart is open",
        "I attract true love",
        "Love defines my life",
        "I am love personified",
        "My love is valued",
        "Love flows abundantly",
        "I deserve great love",
        "My heart attracts love",
        "Love is everywhere",
        "I embrace all love",
        "My relationships are blessed",
        "Love empowers me",
        "I am loved completely",
        "My love life is beautiful",
        "Love heals me",
        "I radiate pure love",
        "Love is my gift",
        "I attract loving souls",
        "My heart is loving",
        "Love grows within me",
        "I am worthy of affection",
        "Love enriches me",
        "My love is infinite",
        "I embrace love daily",
        "Love surrounds my being",
        "I give love freely",
        "My heart is cherished",
        "Love is my truth",
        "I attract deep love",
        "Love fills my heart",
        "I am loved fully",
        "My relationships are loving",
        "Love is my essence",
        "I deserve beautiful love",
        "My heart radiates love",
        "Love blesses me daily",
        "I am love itself"
    ]
    
    // MARK: - Abundance (81 affirmations)
    static let abundance: [String] = [
        "Abundance flows freely into my life",
        "I am open to receiving unlimited prosperity",
        "The universe provides for all my needs",
        "I attract wealth and abundance naturally",
        "Prosperity is my divine birthright",
        "I live in an abundant universe",
        "Money flows to me easily",
        "I am a magnet for financial abundance",
        "Wealth constantly flows into my life",
        "I am worthy of financial freedom",
        "Abundance surrounds me everywhere",
        "I attract prosperity effortlessly",
        "My income increases constantly",
        "I am financially free",
        "Wealth comes to me from all directions",
        "I embrace financial abundance",
        "Money loves me",
        "I am prosperous in all ways",
        "Abundance is my natural state",
        "I attract lucrative opportunities",
        "My wealth grows exponentially",
        "I deserve financial prosperity",
        "Money flows to me abundantly",
        "I am rich in every way",
        "Prosperity fills my life",
        "I attract unlimited abundance",
        "My finances are thriving",
        "Wealth is drawn to me",
        "I live abundantly",
        "Money comes easily to me",
        "I am financially blessed",
        "Abundance is everywhere I look",
        "I prosper beyond my dreams",
        "Wealth supports my purpose",
        "I attract financial miracles",
        "My abundance overflows",
        "I am wealthy and grateful",
        "Prosperity flows naturally",
        "I deserve to be rich",
        "Money multiplies for me",
        "I embrace total abundance",
        "Wealth is my reality",
        "I attract golden opportunities",
        "My life is prosperous",
        "Abundance follows me",
        "I am financially secure",
        "Money appreciates me",
        "I prosper daily",
        "Wealth finds me easily",
        "I am abundant now",
        "Prosperity is mine",
        "I attract riches",
        "My abundance is limitless",
        "Wealth embraces me",
        "I deserve prosperity",
        "Money loves being with me",
        "I am richly blessed",
        "Abundance defines my life",
        "I attract wealth daily",
        "My prosperity expands",
        "I am financially abundant",
        "Wealth flows freely",
        "I embrace being rich",
        "Money is my friend",
        "I prosper endlessly",
        "Abundance loves me",
        "I am forever prosperous",
        "Wealth is natural to me",
        "I attract massive abundance",
        "My riches grow",
        "I deserve wealth",
        "Money is abundant",
        "I am prosperous always",
        "Wealth supports me",
        "I embrace prosperity",
        "Abundance is unlimited",
        "I attract all I need",
        "My wealth is secure",
        "I am blessed abundantly",
        "Prosperity is forever",
        "I am truly abundant"
    ]
    
    // MARK: - Relationships (63 affirmations)
    static let relationships: [String] = [
        "I attract healthy, loving relationships",
        "My relationships are harmonious and fulfilling",
        "I communicate openly and honestly",
        "I am surrounded by supportive people",
        "My connections are meaningful and deep",
        "I attract people who appreciate me",
        "My relationships bring me joy",
        "I am worthy of healthy love",
        "I nurture my relationships with care",
        "My bonds grow stronger daily",
        "I attract positive connections",
        "My friendships are genuine",
        "I communicate with compassion",
        "My relationships are balanced",
        "I attract loyal friends",
        "My connections are authentic",
        "I am valued in relationships",
        "My bonds are unbreakable",
        "I attract understanding partners",
        "My relationships thrive",
        "I communicate my needs clearly",
        "My connections are blessed",
        "I attract respectful people",
        "My friendships are lasting",
        "I am a good friend",
        "My relationships are healthy",
        "I attract kindred spirits",
        "My bonds are sacred",
        "I nurture those I love",
        "My connections are deep",
        "I attract harmonious relationships",
        "My friendships are treasures",
        "I communicate with love",
        "My relationships evolve",
        "I attract great people",
        "My bonds are strong",
        "I am blessed with love",
        "My connections matter",
        "I attract soulful friends",
        "My relationships are gifts",
        "I communicate authentically",
        "My bonds are precious",
        "I attract like-minded souls",
        "My friendships are joyful",
        "I nurture with patience",
        "My connections are valued",
        "I attract wonderful partners",
        "My relationships are sacred",
        "I communicate effectively",
        "My bonds are meaningful",
        "I attract good energy",
        "My friendships flourish",
        "I am relationship-blessed",
        "My connections are loving",
        "I attract real friends",
        "My relationships are fulfilling",
        "I communicate clearly",
        "My bonds are loving",
        "I attract my tribe",
        "My friendships are strong",
        "I nurture with love",
        "My connections are real",
        "I attract beautiful souls"
    ]
    
    // MARK: - Creativity (63 affirmations)
    static let creativity: [String] = [
        "My creativity flows freely and abundantly",
        "I am a channel for creative inspiration",
        "Creative ideas come to me easily",
        "I express my unique creative vision",
        "My imagination is limitless",
        "I am naturally creative and artistic",
        "Creativity is my natural expression",
        "I bring fresh ideas to everything I do",
        "My creative potential is unlimited",
        "I trust my creative instincts",
        "I am inspired every day",
        "My creativity solves problems",
        "I express myself creatively",
        "Creative energy flows through me",
        "I am an innovative thinker",
        "My ideas are valuable",
        "I embrace my artistic side",
        "Creativity comes naturally to me",
        "I am creatively gifted",
        "My imagination knows no bounds",
        "I create with passion",
        "Creative solutions find me",
        "I am an original thinker",
        "My art has meaning",
        "I embrace creative risks",
        "Inspiration surrounds me",
        "I am creatively alive",
        "My ideas matter",
        "I create with confidence",
        "Creative blocks dissolve",
        "I am artistically talented",
        "My vision is unique",
        "I embrace my creativity",
        "Ideas flow abundantly",
        "I am a creative force",
        "My art is valuable",
        "I create with joy",
        "Creative power is mine",
        "I am naturally artistic",
        "My creativity expands",
        "I express freely",
        "Inspiration is everywhere",
        "I am creatively blessed",
        "My ideas are brilliant",
        "I create my reality",
        "Creative gifts are mine",
        "I am an artist",
        "My imagination soars",
        "I embrace artistry",
        "Ideas come easily",
        "I am creative genius",
        "My art inspires",
        "I create with love",
        "Creative flow is natural",
        "I am endlessly creative",
        "My vision matters",
        "I express my soul",
        "Creativity defines me",
        "I am inspiration",
        "My creations are beautiful",
        "I embrace creative flow",
        "Ideas are my gift",
        "I am pure creativity"
    ]
    
    // MARK: - Spiritual (63 affirmations)
    static let spiritual: [String] = [
        "I am connected to infinite wisdom",
        "My soul guides my path",
        "I trust the universe completely",
        "Divine energy flows through me",
        "I am one with all creation",
        "My spirit is eternally peaceful",
        "I am guided by higher wisdom",
        "The universe supports my journey",
        "I am aligned with my purpose",
        "Divine love fills my being",
        "I trust my spiritual path",
        "My soul knows the way",
        "I am spiritually awakened",
        "Universe energy guides me",
        "I am divinely protected",
        "My spirit is infinite",
        "I trust cosmic timing",
        "I am spiritually aligned",
        "Divine wisdom leads me",
        "My soul is expanding",
        "I am one with source",
        "The universe loves me",
        "I trust my inner knowing",
        "I am spiritually connected",
        "Divine light guides me",
        "My path is blessed",
        "I am cosmically supported",
        "Spirit flows through me",
        "I trust divine plan",
        "My soul is free",
        "I am universally loved",
        "Divine timing is perfect",
        "I embrace spiritual growth",
        "My spirit soars",
        "I am divinely guided",
        "Universe provides always",
        "I trust my soul",
        "I am spiritually whole",
        "Divine energy empowers me",
        "My path unfolds perfectly",
        "I am source energy",
        "The universe is kind",
        "I trust completely",
        "My spirit is strong",
        "I am divinely blessed",
        "Universe supports me",
        "I embrace my soul",
        "Divine love heals",
        "I am eternally connected",
        "My spirit guides me",
        "I trust the journey",
        "I am spiritually rich",
        "Divine grace is mine",
        "My soul is wise",
        "I am universally blessed",
        "Spirit protects me",
        "I trust my path",
        "I am divinely loved",
        "Universe embraces me",
        "My spirit is light",
        "I am forever guided",
        "Divine wisdom is mine",
        "I am spiritual being"
    ]
    
    // MARK: - Get All Affirmations
    static func getAllAffirmations() -> [Affirmation] {
        var allAffirmations: [Affirmation] = []
        
        // Add Motivation -> maps to Strength
        for text in motivation {
            allAffirmations.append(Affirmation(text: text, category: .strength))
        }
        
        // Add Self Love
        for text in selfLove {
            allAffirmations.append(Affirmation(text: text, category: .selfLove))
        }
        
        // Add Confidence
        for text in confidence {
            allAffirmations.append(Affirmation(text: text, category: .confidence))
        }
        
        // Add Success
        for text in success {
            allAffirmations.append(Affirmation(text: text, category: .success))
        }
        
        // Add Gratitude
        for text in gratitude {
            allAffirmations.append(Affirmation(text: text, category: .gratitude))
        }
        
        // Add Peace
        for text in peace {
            allAffirmations.append(Affirmation(text: text, category: .peace))
        }
        
        // Add Health
        for text in health {
            allAffirmations.append(Affirmation(text: text, category: .health))
        }
        
        // Add Love -> maps to Relationships
        for text in love {
            allAffirmations.append(Affirmation(text: text, category: .relationships))
        }
        
        // Add Abundance
        for text in abundance {
            allAffirmations.append(Affirmation(text: text, category: .abundance))
        }
        
        // Add Relationships
        for text in relationships {
            allAffirmations.append(Affirmation(text: text, category: .relationships))
        }
        
        // Add Creativity
        for text in creativity {
            allAffirmations.append(Affirmation(text: text, category: .creativity))
        }
        
        // Add Spiritual -> maps to Mindfulness
        for text in spiritual {
            allAffirmations.append(Affirmation(text: text, category: .mindfulness))
        }
        
        return allAffirmations
    }
    
    // MARK: - Get Affirmations by Category
    static func getAffirmations(for category: Category) -> [Affirmation] {
        let texts: [String]
        
        switch category {
        case .selfLove:
            texts = selfLove
        case .success:
            texts = success
        case .health:
            texts = health
        case .relationships:
            texts = relationships + love
        case .abundance:
            texts = abundance
        case .confidence:
            texts = confidence
        case .gratitude:
            texts = gratitude
        case .peace:
            texts = peace
        case .creativity:
            texts = creativity
        case .mindfulness:
            texts = spiritual
        case .strength:
            texts = motivation
        case .joy:
            texts = gratitude + selfLove // Joy combines gratitude and self-love
        }
        
        return texts.map { Affirmation(text: $0, category: category) }
    }
    
    // MARK: - Get Random Affirmation
    static func getRandomAffirmation() -> Affirmation {
        let allAffirmations = getAllAffirmations()
        return allAffirmations.randomElement() ?? Affirmation(text: "I am grateful for this moment", category: .gratitude)
    }
    
    // MARK: - Get Time-Based Affirmation
    static func getTimeBasedAffirmation() -> Affirmation {
        let hour = Calendar.current.component(.hour, from: Date())
        
        switch hour {
        case 5..<9:
            // Early morning - strength/motivation
            return motivation.randomElement().map { Affirmation(text: $0, category: .strength) } ?? getRandomAffirmation()
        case 9..<12:
            // Morning - success/confidence
            let combined = success + confidence
            return combined.randomElement().map { Affirmation(text: $0, category: .success) } ?? getRandomAffirmation()
        case 12..<14:
            // Midday - gratitude
            return gratitude.randomElement().map { Affirmation(text: $0, category: .gratitude) } ?? getRandomAffirmation()
        case 14..<17:
            // Afternoon - strength/abundance
            let combined = motivation + abundance
            return combined.randomElement().map { Affirmation(text: $0, category: .strength) } ?? getRandomAffirmation()
        case 17..<20:
            // Evening - gratitude/relationships
            let combined = gratitude + love
            return combined.randomElement().map { Affirmation(text: $0, category: .gratitude) } ?? getRandomAffirmation()
        case 20..<23:
            // Night - peace/self-love
            let combined = peace + selfLove
            return combined.randomElement().map { Affirmation(text: $0, category: .peace) } ?? getRandomAffirmation()
        default:
            // Late night - peace
            return peace.randomElement().map { Affirmation(text: $0, category: .peace) } ?? getRandomAffirmation()
        }
    }
    
    // MARK: - Statistics
    static var totalCount: Int {
        return motivation.count + selfLove.count + confidence.count + success.count +
               gratitude.count + peace.count + health.count + love.count +
               abundance.count + relationships.count + creativity.count + spiritual.count
    }
}

